name: Run Sales ETL Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build-and-run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyarrow

      - name: Run ETL script
        run: python run_etl.py

      - name: Upload sales report artifact
        uses: actions/upload-artifact@v4
        with:
          name: sales-report
          path: output/sales_report.parquet